services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin12345!
      - POSTGRES_DB=NotesDb
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    networks:
      - bridgenetwork
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    expose:
      - 1433
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin12345!
    volumes:
      - mssqlvolume:/var/opt/mssql
    networks:
      - bridgenetwork
    restart: always

  webapi:
    image: webapi_image
    build:
      context: .
      dockerfile: webapi.Dockerfile
    container_name: webapi_container
    expose:
      - 4000
    ports:
      - 7000:4000
    environment:
      - ASPNETCORE_URLS=http://+:4000
    networks:
      - bridgenetwork
    depends_on:
      - postgres
      - mssql
    restart: always

networks:
  bridgenetwork:
    driver: bridge

volumes:
  postgresvolume:
  mssqlvolume: